### ISSUE TITLE
Got   runtime  error: slice bounds out of range

### ISSUE THREAD

**Issue by cjj2003** [wxbool/video-srt#1]
I use video-srt-gui-temp-0.1.5 and got runtime  error: slice bounds out of range for some files.

**Comment by wxbool** [comment]
windows-gui 版本已修复此问题。

我稍候会修复这个问题。

**Comment by wxbool** [comment]
已提交此问题的修复版本，你可以到 https://github.com/wxbool/video-srt-windows/releases 下载最新的打包程序（v0.1.6）。
你只需要将 “videosrt.exe” 的可执行文件更换即可

**Comment by cjj2003** [comment]
Had a test on another mp3 file and got the same error.
错误：runtime error: slice bounds out of range

**Comment by wxbool** [comment]
> Had a test on another mp3 file and got the same error.
> 错误：runtime error: slice bounds out of range


你可以将出现错误的 .mp3 文件链接发出来供我进行测试吗？
以及你使用了什么语言识别引擎，中文 或者 英文？

**Comment by wxbool** [comment]
已提交此问题的修复版本，你可以到 https://github.com/wxbool/video-srt-windows/releases 下载最新的打包程序（v0.2.1）
